# for development purpose only
version: '3.9'
services:
  postgres:
    container_name: transfer_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresdata:/var/lib/postgres
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
  postgresdata:
